# For local development, we turn on the Ingress controller and set up a simple
# local ingress.
ingress:
  # -- Enable local ingress for local development.
  enabled: false

  # -- Disable the SSL-Redirect explicitly because it only applies to
  # ALB-ingress controllers.
  sslRedirect: false

ports:
  - name: http
    containerPort: 80
    protocol: TCP
    # Optional flag to override the client-facing port for service requests.
    port:


topologyKey: kubernetes.io/hostname
enableTopologySpread: false
terminationGracePeriodSeconds: 30
autoscaling:
  enabled: true

secrets:
  TEST_SECRET: junksecret

network:
  allowedNamespaces: [foo, bar]
